spring.application.name=eventmanager
spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#=======================================================================================
server.address=0.0.0.0
server.port=8080

jwt.secret=MarquiseSecretKeyForJWT2024VeryLongAndSecureDoNotShareInProduction
jwt.expiration=86400000
cors.allowed-origins=*

# --- Configuration mail Gmail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# URL reset password
app.reset-password.url=${RESET_PASSWORD_URL}
app.reset-password.expiration-minutes=15