spring.application.name=eventmanager

spring.datasource.url=jdbc:postgresql://${HOST}:${PORTB}/${DATABASE}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#=======================================================================================
server.address=0.0.0.0
server.port=${PORT:8080}

jwt.secret=MarquiseSecretKeyForJWT2024VeryLongAndSecureDoNotShareInProduction
jwt.expiration=86400000
cors.allowed-origins=*

# =========================
# CONFIGURATION MAIL GMAIL
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8


# =========================
# URL APPLICATION
# =========================

# URL publique Railway du backend
server.base-url=${SERVER_URL}

# URL frontend (Angular / React / mobile)
app.frontend.url=${FRONTEND_URL}

# URL reset password
app.reset-password.url=${SERVER_URL}/api/auth/reset-password

# Expiration token reset password
app.reset-password.expiration-minutes=15


# =========================
# UPLOAD
# =========================
upload.dir=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

